import js from "@eslint/js"
import globals from "globals"
import prettier from "eslint-config-prettier"
import tseslint from "typescript-eslint"

export default tseslint.config(
  // web/ is the Next.js rewrite (REACT_REWRITE_PLAN.md). It is a self-contained
  // sub-project with its own TypeScript toolchain and its own lint step, and
  // its build output under web/.next/ is minified bundles. This config has no
  // TS project service pointed at it and would report thousands of false
  // positives on both.
  //
  // The `*.js` twins next to the browser `*.ts` sources below are generated by
  // `npm run build:browser` (tsc) — lint the source, not the compiled artifact.
  {
    ignores: [
      "node_modules/**",
      "**/node_modules/**",
      "assets/cards/**",
      ".vercel/**",
      "web/**",
      // automation/ and process/ are deliberately isolated sub-projects (own
      // package.json, own module format, own dependency tree — the "C8"
      // boundary referenced throughout this codebase's comments) and always
      // have been outside this config's scope. They stayed plain JS/CJS-vs-
      // ESM specific enough that folding them into one root lint config
      // surfaces a pile of pre-existing, unrelated style issues rather than
      // anything this config is meant to catch. Give each its own eslint
      // config under its own directory if/when they want linting.
      "automation/**",
      "process/**",
      "assets/*.js",
      "verify/app.js",
      "status/app.js",
      "list/app.js",
      "ranking/app.js",
      "admin/app.js",
      "upload/app.js",
      "lib/line-receipt-flex.js",
      // Generated by `npm run build:constants` — see src/constants.ts's own
      // header comment for why this compiled twin needs to exist at all.
      "src/constants.js",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // The root server (main.ts) and its shared CommonJS-compiled libs. These
  // write `import` at the syntax level (so ESLint needs `sourceType: "module"`
  // to parse them) even though they keep `require()`/`module.exports` for the
  // *runtime* shape — see each file's own header comment for why (lazy
  // require()s, the lib/line-receipt-flex isomorphic UMD pattern). Hence
  // `no-require-imports` is off here specifically: it is a deliberate choice
  // in this file group, not an artifact of a half-finished conversion.
  {
    files: ["main.ts", "lib/*.ts", "src/**/*.ts", "scripts/**/*.mts"],
    ignores: ["lib/line-receipt-flex.ts"],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: "latest",
      globals: { ...globals.node },
    },
    rules: {
      // Vendored/legacy code leans on `any` at API boundaries (axios error
      // bodies, ExcelJS cell values, Drive/Gmail API JSON) on purpose — see
      // each conversion's own comments. Downgrading rather than disabling
      // keeps it visible without failing CI on every pragmatic escape hatch.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // Browser scripts served to the LIFF pages. `assets/` holds the shared
  // helpers; the six page directories hold each page's own app.ts. These were
  // previously outside every `files` block, so they fell back to the bare
  // recommended config with NO globals declared — every use of `fetch`,
  // `location`, `localStorage`, `console` etc. was reported as no-undef, which
  // buried any real finding under ~56 false ones.
  {
    files: [
      "assets/**/*.ts",
      "verify/app.ts",
      "status/app.ts",
      "list/app.ts",
      "ranking/app.ts",
      "admin/app.ts",
      "upload/app.ts",
    ],
    languageOptions: {
      sourceType: "script",
      ecmaVersion: "latest",
      globals: {
        ...globals.browser,
        // Loaded from CDNs / injected by the page, not bundled.
        supabase: "readonly",
        liff: "readonly",
        P4P: "writable",
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      // These are byte-faithful mechanical ports of pre-existing legacy
      // scripts (see each file's own header comment) — `var` and an unused
      // `catch (e) {}` binding are the original files' own style, kept
      // deliberately rather than "improved" during the TS conversion.
      "no-var": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", caughtErrors: "none" }],
      // `cond ? a() : b()` used purely for its side effect, no assignment —
      // upload/app.js's original randomId() already wrote it this way.
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },

  // lib/ is loaded from BOTH runtimes: main.ts require()s these files and the
  // /upload/ page loads line-receipt-flex.js with a <script src>. Hence both
  // sets of globals — the UMD-lite wrapper in that file genuinely reads
  // `module`, `require` and `self` in the same source.
  {
    files: ["lib/line-receipt-flex.ts"],
    languageOptions: {
      sourceType: "script",
      ecmaVersion: "latest",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // Ambient .d.ts declaration files — global scope by definition.
  {
    files: ["**/*.d.ts"],
    languageOptions: {
      sourceType: "script",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  // Root test suite (node:test, ESM) — the tests themselves stay plain .mjs;
  // only the sources they import were converted to TypeScript.
  {
    files: ["lib/__tests__/**/*.mjs"],
    languageOptions: {
      sourceType: "module",
      ecmaVersion: "latest",
      globals: { ...globals.node },
    },
  },

  // Turn off rules that conflict with Prettier formatting.
  prettier,
)
